spring:
  application:
    name: events-service
  datasource:
    username: eventsadmin
    password: eventssuper
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://events-postgresql:5432/events_db
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:consul}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true



#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://service-registry:8761/eureka/